### ISSUE TITLE
Players with (Server Operator) Permissions get kicked?

### ISSUE THREAD

**Issue by GunnableScum** [disymayufei/Fabric-Bungeecord-Proxy#3]
Hey there, if anybody is still working on this, which I doubt, as there is probably more support for Velocity instead of Waterfall but I'll try shooting my shot. I am running a Waterfall Proxy with a Paper Lobby Server and a Fabric Modded Server, I am an operator on the Fabric Server, but if I connect using the Proxy, I get kicked from the server, the Server Console does not print a warning or error, I just get "Disconnected."

Here's a short bit of the Logs for a possible clue of what's up:
```
[12:59:56] [Server thread/INFO]: GunnableScum[/XXX.XXX.XXX.XXX:XXXXX] logged in with entity id 260 at (8.5, 74.0, 8.5)
[12:59:56] [Server thread/INFO]: [voicechat] Using Fabric Permissions API
[12:59:56] [Server thread/INFO]: GunnableScum joined the game
[12:59:57] [Server thread/INFO]: GunnableScum lost connection: Disconnected
[12:59:57] [Server thread/INFO]: GunnableScum left the game
[12:59:57] [Server thread/INFO]: [voicechat] Disconnecting client GunnableScum
[12:59:57] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2058ms or 41 ticks behind
[12:59:57] [Server thread/WARN]: handleDisconnection() called twice
```

For any Configuration help or general Info on how to fix would be great! Thank you!

**Comment by disymayufei** [comment]
I suspect that this issue may be caused by conflicting mods. Can you help me further determine if this problem is caused by specific mods?

**Comment by disymayufei** [comment]
I suspect that this issue may be caused by conflicting mods. Can you help me further determine if this problem is caused by specific mods?

**Comment by GunnableScum** [comment]
Hey there, Glad to see somebody is still working on this! Here, I have a server log available for you, one from my Fabric-Server and a (shortened, as it doesn't contain other useful information) one from my Proxy. Mod List is available in the Fabric Log.
[fabric.log](https://github.com/disymayufei/Fabric-Bungeecord-Proxy/files/13523195/fabric.log)
[proxy.log](https://github.com/disymayufei/Fabric-Bungeecord-Proxy/files/13523196/proxy.log)

**Comment by disymayufei** [comment]
which proxy you are using now? bungeecord, waterfall or velocity(bungeecord compatible mode)

**Comment by GunnableScum** [comment]
> ...I am running a Waterfall Proxy with a Paper Lobby Server and a Fabric Modded Server...

Still unchanged. Running waterfall.

**Comment by disymayufei** [comment]
> > ...I am running a Waterfall Proxy with a Paper Lobby Server and a Fabric Modded Server...
> 
> Still unchanged. Running waterfall.

Can you try velocity(bungee cpmpatible mode)?

**Comment by GunnableScum** [comment]
I'll try that later today and update you when I did, since I'm not home rn, but I'll try that

**Comment by disymayufei** [comment]
> I'll try that later today and update you when I did, since I'm not home rn, but I'll try that

ok, but I will reply you later cause i'm chinese and it's midnight now in china

**Comment by GunnableScum** [comment]
Hello again! I'm very sorry I took so long to respond, my Computer broke down and I had to get it fixed, and I also had a lot going on because of celebrating Christmas with my Family, and there's also a [protest](https://www.youtube.com/watch?v=508Tvri2CjQ) going on in Germany blocking pretty much everything right now. So I'm really sorry. Anyways, to your Question now.

> > > ...I am running a Waterfall Proxy with a Paper Lobby Server and a Fabric Modded Server...
> > 
> > 
> > Still unchanged. Running waterfall.
> 
> Can you try velocity(bungee cpmpatible mode)?

Using Velocity yields the same result, I still get kicked from the Server after joining.
EDIT: The Velocity Console announces the following:
> [06:30:40 ERROR]: [server connection] GunnableScum -> fabric: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@705ae00e

**Comment by paulzzh** [comment]
Can confirm on fabric 1.21 and velocity-3.3.0-SNAPSHOT-398.
Operators get kicked.
```
[05:52:32 INFO]: [server connection] Paulzzh -> SU has connected
[05:52:32 ERROR]: [server connection] Paulzzh -> SU: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@6f1573ad
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket Direction CLIENTBOUND Protocol 1.21 State PLAY ID 11
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:131) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:86) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT[detached from 2230023.VE]
[mc@localhost ~]$ screen -x SUstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.IllegalArgumentException: Unknown node type 3
        at com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket.deserializeNode(AvailableCommandsPacket.java:219) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket.decode(AvailableCommandsPacket.java:88) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:84) ~[velocity-3.3.0-SNAPSHOT-398.jar:3.3.0-SNAPSHOT (git-350ea7f3-b398)]
        ... 29 more
```

```
---- Minecraft Network Protocol Error Report ----
// Wait, was the last bit one or zero?

Time: 2024-06-16 05:50:10
Description: Packet handling error

io.netty.handler.codec.EncoderException: Sending unknown packet 'serverbound/minecraft:chat_session_update'
	at net.minecraft.class_9136.method_56426(class_9136.java:47)
	at net.minecraft.class_9136.encode(class_9136.java:14)
	at net.minecraft.class_2545.method_10838(class_2545.java:26)
	at net.minecraft.class_2545.encode(class_2545.java:12)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
	at net.minecraft.class_2535$2.write(class_2535.java:530)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
	at net.minecraft.class_2535.method_36942(class_2535.java:350)
	at net.minecraft.class_2535.method_52917(class_2535.java:345)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Netty Client IO #3
Stacktrace:
	at net.minecraft.class_2547.method_55622(class_2547.java:33)

-- Connection --
Details:
	Protocol: configuration
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: fabric (Velocity)
Stacktrace:
	at net.minecraft.class_2547.method_55622(class_2547.java:33)
	at net.minecraft.class_2600.method_59803(class_2600.java:62)
	at net.minecraft.class_8673.method_60882(class_8673.java:136)
	at net.minecraft.class_8673.method_60881(class_8673.java:127)
	at net.minecraft.class_2535.exceptionCaught(class_2535.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:69)
	at io.netty.channel.ChannelFutureListener$3.operationComplete(ChannelFutureListener.java:65)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at net.minecraft.class_2535.method_36942(class_2535.java:364)
	at net.minecraft.class_2535.method_52917(class_2535.java:345)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 232617960 bytes (221 MiB) / 552599552 bytes (527 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 2.81
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.5222
	Graphics card #1 name: Intel(R) HD Graphics 630
	Graphics card #1 vendor: Intel Corporation
	Graphics card #1 VRAM (MiB): 1024.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 27.20.100.9664
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 32634.14
	Virtual memory used (MiB): 9957.48
	Swap memory total (MiB): 16384.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 13561.76, total: 121536.00
	Space in storage for workdir (MiB): available: 312790.47, total: 883713.06
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	Fabric Mods: 
		appleskin: AppleSkin 3.0.2+mc1.21
		chat_heads: Chat Heads 0.12.3
		checkupdate: CheckUpdate 1.0.3
		classic_minecraft_icon: Classic Minecraft Icon 1.1.2
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.61
		customskinloader: CustomSkinLoader 14.19.1
		disableinsecurechattoast: Disable Insecure Chat Toast 1.1.0
		fabric-api: Fabric API 0.100.1+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.65+b559734490
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b9990
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a790
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a790
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa1990
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.11+b559734490
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.12+7f945d5b90
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.2.1+d153f34490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a790
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.22+6a6dfa1990
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.6+16c4ae2590
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9990
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b9990
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8c90
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92190
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.0+00ab0a6390
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.9+98a7dbbb90
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.9+6573ed8c90
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c90
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b90
			fabric-networking-api-v1: Fabric Networking API (v1) 4.1.0+686dcdce90
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.10+d132107690
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c90
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.8+6573ed8c90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.21+b9828ba390
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.16+fe474d6b90
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.3+cc9f121a90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.66+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b559734490
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.69+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.3+d132107690
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f34490
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.3+b559734490
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.78+b559734490
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.12+b559734490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8c90
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		hideexperimentalwarning: Hide Experimental Warning 1.1
		hidemodded: HideModded 1.0.1
		jade: Jade 15.0.4+fabric
		java: Java HotSpot(TM) 64-Bit Server VM 21
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.0-beta.2
		mousetweaks: Mouse Tweaks 2.26
		no-telemetry: No Telemetry 1.8.0
		noreportbutton: No Report Button 1.5.0
		skinlayers3d: 3d-Skin-Layers 1.6.6
		urlimg: urlimg 1.0.2
		zmusic: ZMusic Mod 3.2.0
```
